import { IIconSchema, IZedIconSchema } from '..';

export const schema: IIconSchema = {
  iconDefinitions: {
    _file: { iconPath: '' },
    _folder: { iconPath: '' },
    _folder_open: { iconPath: '' },
    _root_folder: { iconPath: '' },
    _root_folder_open: { iconPath: '' },
    _file_light: { iconPath: '' },
    _folder_light: { iconPath: '' },
    _folder_light_open: { iconPath: '' },
    _root_folder_light: { iconPath: '' },
    _root_folder_light_open: { iconPath: '' },
  },
  file: '_file',
  folder: '_folder',
  folderExpanded: '_folder_open',
  rootFolder: '_root_folder',
  rootFolderExpanded: '_root_folder_open',
  folderNames: {},
  folderNamesExpanded: {},
  fileExtensions: {},
  fileNames: {},
  languageIds: {},
  light: {
    file: '_file_light',
    folder: '_folder_light',
    folderExpanded: '_folder_light_open',
    rootFolder: '_root_folder_light',
    rootFolderExpanded: '_root_folder_light_open',
    folderNames: {},
    folderNamesExpanded: {},
    fileExtensions: {},
    fileNames: {},
    languageIds: {},
  },
  hidesExplorerArrows: false,
};

export const zedSchema: IZedIconSchema = {
  $schema: 'https://zed.dev/schema/icon_themes/v0.3.0.json',
  name: 'VSCode Icons for Zed',
  author: 'Roberto Huertas <roberto.huertas@outlook.com>',
  themes: [
    {
      name: 'VSCode Icons for Zed (Dark)',
      appearance: 'dark',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Dark Official Icons)',
      appearance: 'dark',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Dark Angular)',
      appearance: 'dark',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Dark NestJS)',
      appearance: 'dark',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Light)',
      appearance: 'light',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Light Official Icons)',
      appearance: 'light',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Light Angular)',
      appearance: 'light',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
    {
      name: 'VSCode Icons for Zed (Light NestJS)',
      appearance: 'light',
      directory_icons: {
        collapsed: '',
        expanded: '',
      },
      chevron_icons: {
        collapsed: '',
        expanded: '',
      },
      named_directory_icons: {},
      file_stems: {},
      file_suffixes: {},
      file_icons: {},
    },
  ],
};
