import { IIconSchema } from '..';

export const schema: IIconSchema = {
  iconDefinitions: {
    _file: { iconPath: '' },
    _folder: { iconPath: '' },
    _folder_open: { iconPath: '' },
    _root_folder: { iconPath: '' },
    _root_folder_open: { iconPath: '' },
    _file_light: { iconPath: '' },
    _folder_light: { iconPath: '' },
    _folder_light_open: { iconPath: '' },
    _root_folder_light: { iconPath: '' },
    _root_folder_light_open: { iconPath: '' },
  },
  file: '_file',
  folder: '_folder',
  folderExpanded: '_folder_open',
  rootFolder: '_root_folder',
  rootFolderExpanded: '_root_folder_open',
  folderNames: {},
  folderNamesExpanded: {},
  fileExtensions: {},
  fileNames: {},
  languageIds: {},
  light: {
    file: '_file_light',
    folder: '_folder_light',
    folderExpanded: '_folder_light_open',
    rootFolder: '_root_folder_light',
    rootFolderExpanded: '_root_folder_light_open',
    folderNames: {},
    folderNamesExpanded: {},
    fileExtensions: {},
    fileNames: {},
    languageIds: {},
  },
  hidesExplorerArrows: false,
};
