version: "2"
checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
plugins:
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
      MD036:
        enabled: false
  nodesecurity:
    enabled: true
  tslint:
    enabled: false
exclude_patterns:
  - ".*"
  - ".*/"
  - "*.*"
  - "!*.md"
  - "!src/**/*.ts"
  - "!test/**/*.ts"
