import { ILanguageCollection } from '../models';

export const languages: ILanguageCollection = {
  actionscript: { ids: 'nextgenas', defaultExtension: 'as' },
  al: { ids: 'al', defaultExtension: 'al' },
  ansible: { ids: 'ansible', defaultExtension: 'ansible' },
  antlr: { ids: 'antlr', defaultExtension: 'g4' },
  anyscript: { ids: 'anyscript', defaultExtension: 'any' },
  apache: { ids: 'apacheconf', defaultExtension: 'htaccess' },
  apex: { ids: 'apex', defaultExtension: 'cls' },
  apib: { ids: 'apiblueprint', defaultExtension: 'apib' },
  applescript: { ids: 'applescript', defaultExtension: 'applescript' },
  asp: { ids: ['asp', 'asp (html)'], defaultExtension: 'asp' },
  assembly: { ids: ['arm', 'asm'], defaultExtension: 'asm' },
  autohotkey: { ids: 'ahk', defaultExtension: 'ahk' },
  autoit: { ids: 'autoit', defaultExtension: 'au3' },
  avro: { ids: 'avro', defaultExtension: 'avcs' },
  bat: { ids: 'bat', defaultExtension: 'bat' },
  bazel: { ids: 'bazel', defaultExtension: 'bzl' },
  bibtex: { ids: 'bibtex', defaultExtension: 'bib' },
  blade: { ids: ['blade', 'laravel-blade'], defaultExtension: 'blade.php' },
  bolt: { ids: 'bolt', defaultExtension: 'bolt' },
  c: { ids: 'c', defaultExtension: 'c' },
  c_al: { ids: 'c-al', defaultExtension: 'cal' },
  cabal: { ids: 'cabal', defaultExtension: 'cabal' },
  cfc: { ids: 'cfc', defaultExtension: 'cfc' },
  cfm: { ids: 'cfmhtml', defaultExtension: 'cfm' },
  clojure: { ids: 'clojure', defaultExtension: 'clojure' },
  cmake: { ids: 'cmake', defaultExtension: 'cmake' },
  cmakecache: { ids: 'cmake-cache', defaultExtension: 'CMakeCache.txt' },
  cobol: { ids: 'cobol', defaultExtension: 'cbl' },
  coffeescript: { ids: 'coffeescript', defaultExtension: 'coffee' },
  coldfusion: { ids: ['cfml', 'lang-cfml'], defaultExtension: 'cfml' },
  cpp: { ids: 'cpp', defaultExtension: 'cpp' },
  crystal: { ids: 'crystal', defaultExtension: 'cr' },
  csharp: { ids: 'csharp', defaultExtension: 'cs' },
  css: { ids: 'css', defaultExtension: 'css' },
  cucumber: { ids: 'feature', defaultExtension: 'feature' },
  dal: { ids: 'dal', defaultExtension: 'dal' },
  dart: { ids: 'dart', defaultExtension: 'dart' },
  diff: { ids: 'diff', defaultExtension: 'diff' },
  dlang: { ids: ['d', 'dscript', 'dml', 'diet'], defaultExtension: 'd' },
  dockerfile: { ids: 'dockerfile', defaultExtension: 'dockerfile' },
  doxygen: { ids: 'doxygen', defaultExtension: 'dox' },
  drools: { ids: 'drools', defaultExtension: 'drl' },
  dylanlang: { ids: ['dylan', 'dylan-lid'], defaultExtension: 'dylan' },
  dustjs: { ids: 'dustjs', defaultExtension: 'dust' },
  edge: { ids: 'edge', defaultExtension: 'edge' },
  eex: { ids: ['eex', 'html-eex'], defaultExtension: 'eex' },
  elastic: { ids: 'es', defaultExtension: 'es' },
  elixir: { ids: 'elixir', defaultExtension: 'ex' },
  elm: { ids: 'elm', defaultExtension: 'elm' },
  erb: { ids: 'erb', defaultExtension: 'erb' },
  erlang: { ids: 'erlang', defaultExtension: 'erl' },
  fortran: { ids: ['fortran', 'fortran-modern'], defaultExtension: 'f' },
  freemarker: { ids: 'ftl', defaultExtension: 'ftl' },
  fsharp: { ids: 'fsharp', defaultExtension: 'fs' },
  galen: { ids: 'galen', defaultExtension: 'gspec' },
  gamemaker: { ids: 'gml-gms', defaultExtension: 'gml' },
  gamemaker2: { ids: 'gml-gms2', defaultExtension: 'gml' },
  gamemaker81: { ids: 'gml-gm81', defaultExtension: 'gml' },
  git: { ids: ['git-commit', 'git-rebase'], defaultExtension: 'git' },
  glsl: { ids: 'glsl', defaultExtension: 'glsl' },
  go: { ids: 'go', defaultExtension: 'go' },
  godot: { ids: 'gdscript', defaultExtension: 'gd' },
  graphql: { ids: 'graphql', defaultExtension: 'gql' },
  graphviz: { ids: 'dot', defaultExtension: 'gv' },
  groovy: { ids: 'groovy', defaultExtension: 'groovy' },
  haml: { ids: 'haml', defaultExtension: 'haml' },
  handlebars: { ids: 'handlebars', defaultExtension: 'hbs' },
  harbour: { ids: 'harbour', defaultExtension: 'prg' },
  haskell: { ids: 'haskell', defaultExtension: 'hs' },
  haxe: { ids: ['haxe', 'hxml', 'Haxe AST dump'], defaultExtension: 'haxe' },
  hlsl: { ids: 'hlsl', defaultExtension: 'hlsl' },
  hosts: { ids: 'hosts', defaultExtension: 'hosts' },
  html: { ids: 'html', defaultExtension: 'html' },
  http: { ids: 'http', defaultExtension: 'http' },
  ini: { ids: 'ini', defaultExtension: 'ini' },
  io: { ids: 'io', defaultExtension: 'io' },
  latex: { ids: 'latex', defaultExtension: 'tex' },
  java: { ids: 'java', defaultExtension: 'java' },
  javascript: { ids: 'javascript', defaultExtension: 'js' },
  javascriptreact: { ids: 'javascriptreact', defaultExtension: 'jsx' },
  jekyll: { ids: 'jekyll', defaultExtension: 'jekyll' },
  jinja: { ids: 'jinja', defaultExtension: 'jinja' },
  json: { ids: 'json', defaultExtension: 'json' },
  jsonc: { ids: 'jsonc', defaultExtension: 'json' },
  json5: { ids: 'json5', defaultExtension: 'json5' },
  julia: { ids: ['julia', 'juliamarkdown'], defaultExtension: 'jl' },
  iodine: { ids: 'iodine', defaultExtension: 'id' },
  kivy: { ids: 'kivy', defaultExtension: 'kv' },
  kos: { ids: 'kos', defaultExtension: 'ks' },
  kotlin: { ids: 'kotlin', defaultExtension: 'kt' },
  less: { ids: 'less', defaultExtension: 'less' },
  lisp: { ids: 'lisp', defaultExtension: 'lisp' },
  literatehaskell: { ids: ['literate haskell'], defaultExtension: 'lhs' },
  lolcode: { ids: 'lolcode', defaultExtension: 'lol' },
  lsl: { ids: 'lsl', defaultExtension: 'lsl' },
  lua: { ids: 'lua', defaultExtension: 'lua' },
  makefile: { ids: 'makefile', defaultExtension: 'mk' },
  markdown: { ids: 'markdown', defaultExtension: 'md' },
  marko: { ids: 'marko', defaultExtension: 'marko' },
  matlab: { ids: 'matlab', defaultExtension: 'mat' },
  maxscript: { ids: 'maxscript', defaultExtension: 'ms' },
  mediawiki: { ids: 'mediawiki', defaultExtension: 'mediawiki' },
  mjml: { ids: 'mjml', defaultExtension: 'mjml' },
  mlang: { ids: ['mlang', 'powerquerymlanguage'], defaultExtension: 'pq' },
  mojolicious: { ids: 'mojolicious', defaultExtension: 'ep' },
  mson: { ids: 'mson', defaultExtension: 'mson' },
  nim: { ids: ['nim', 'nimble'], defaultExtension: 'nim' },
  nsis: { ids: ['nsis', 'nfl', 'nsl', 'bridlensis'], defaultExtension: 'nsi' },
  nunjucks: { ids: 'nunjucks', defaultExtension: 'nunjucks' },
  objectivec: { ids: 'objective-c', defaultExtension: 'm' },
  objectivecpp: { ids: 'objective-cpp', defaultExtension: 'mm' },
  ocaml: { ids: ['ocaml', 'ocamllex', 'menhir'], defaultExtension: 'ml' },
  openEdge: { ids: 'abl', defaultExtension: 'w' },
  openHAB: { ids: 'openhab', defaultExtension: 'things' },
  pascal: { ids: ['pascal', 'objectpascal'], defaultExtension: 'pas' },
  perl: { ids: 'perl', defaultExtension: 'pl' },
  perl6: { ids: 'perl6', defaultExtension: 'pl6' },
  php: { ids: 'php', defaultExtension: 'php' },
  plaintext: { ids: 'plaintext', defaultExtension: 'txt' },
  plsql: { ids: ['plsql', 'oracle'], defaultExtension: 'ddl' },
  polymer: { ids: 'polymer', defaultExtension: 'polymer' },
  postcss: { ids: 'postcss', defaultExtension: 'pcss' },
  powershell: { ids: 'powershell', defaultExtension: 'ps1' },
  processinglang: { ids: 'pde', defaultExtension: 'pde' },
  prolog: { ids: 'prolog', defaultExtension: 'pro' },
  prometheus: { ids: 'prometheus', defaultExtension: 'rules' },
  properties: { ids: 'properties', defaultExtension: 'properties' },
  protobuf: { ids: ['proto3', 'proto'], defaultExtension: 'proto' },
  pug: { ids: 'jade', defaultExtension: 'pug' },
  puppet: { ids: 'puppet', defaultExtension: 'pp' },
  purescript: { ids: 'purescript', defaultExtension: 'purs' },
  python: { ids: 'python', defaultExtension: 'py' },
  qlik: { ids: 'qlik', defaultExtension: 'qvs' },
  r: { ids: 'r', defaultExtension: 'r' },
  racket: { ids: 'racket', defaultExtension: 'rkt' },
  razor: { ids: 'razor', defaultExtension: 'cshtml' },
  raml: { ids: 'raml', defaultExtension: 'raml' },
  reason: { ids: 'reason', defaultExtension: 're' },
  restructuredtext: { ids: 'restructuredtext', defaultExtension: 'rst' },
  riot: { ids: 'riot', defaultExtension: 'tag' },
  robot: { ids: 'robot', defaultExtension: 'robot' },
  ruby: { ids: 'ruby', defaultExtension: 'rb' },
  rust: { ids: 'rust', defaultExtension: 'rs' },
  sbt: { ids: 'sbt', defaultExtension: 'sbt' },
  scala: { ids: 'scala', defaultExtension: 'scala' },
  scilab: { ids: 'scilab', defaultExtension: 'sce' },
  scss: { ids: 'scss', defaultExtension: 'scss' },
  sdlang: { ids: 'sdl', defaultExtension: 'sdl' },
  shaderlab: { ids: 'shaderlab', defaultExtension: 'shader' },
  shellscript: { ids: 'shellscript', defaultExtension: 'sh' },
  slice: { ids: ['slice'], defaultExtension: 'ice' },
  slim: { ids: ['slim'], defaultExtension: 'slim' },
  silverstripe: { ids: 'silverstripe', defaultExtension: 'ss' },
  skipper: { ids: ['eskip'], defaultExtension: 'eskip' },
  smarty: { ids: ['smarty'], defaultExtension: 'tpl' },
  snort: { ids: ['snort'], defaultExtension: 'snort' },
  solidity: { ids: ['solidity'], defaultExtension: 'sol' },
  sqf: { ids: 'sqf', defaultExtension: 'sqf' },
  sql: { ids: 'sql', defaultExtension: 'sql' },
  squirrel: { ids: 'squirrel', defaultExtension: 'nut' },
  stata: { ids: 'stata', defaultExtension: 'do' },
  stylable: { ids: 'stylable', defaultExtension: 'st.css' },
  stylus: { ids: 'stylus', defaultExtension: 'styl' },
  swagger: { ids: ['Swagger', 'swagger'], defaultExtension: 'swagger' },
  swift: { ids: 'swift', defaultExtension: 'swift' },
  swig: { ids: 'swig', defaultExtension: 'swig' },
  systemverilog: { ids: 'systemverilog', defaultExtension: 'sv' },
  terraform: { ids: 'terraform', defaultExtension: 'tf' },
  tex: { ids: 'tex', defaultExtension: 'sty' },
  textile: { ids: 'textile', defaultExtension: 'textile' },
  textmatejson: { ids: 'json-tmlanguage', defaultExtension: 'JSON-tmLanguage' },
  textmateyaml: { ids: 'yaml-tmlanguage', defaultExtension: 'YAML-tmLanguage' },
  toml: { ids: 'toml', defaultExtension: 'toml' },
  twig: { ids: 'twig', defaultExtension: 'twig' },
  typescript: { ids: 'typescript', defaultExtension: 'ts' },
  typescriptreact: { ids: 'typescriptreact', defaultExtension: 'tsx' },
  vb: { ids: 'vb', defaultExtension: 'vb' },
  vba: { ids: 'vba', defaultExtension: 'cls' },
  vbscript: { ids: 'vbscript', defaultExtension: 'wsf' },
  velocity: { ids: 'velocity', defaultExtension: 'vm' },
  verilog: { ids: 'verilog', defaultExtension: 'v' },
  vhdl: { ids: 'vhdl', defaultExtension: 'vhdl' },
  viml: { ids: 'viml', defaultExtension: 'vim' },
  volt: { ids: 'volt', defaultExtension: 'volt' },
  vue: { ids: 'vue', defaultExtension: 'vue' },
  wolfram: { ids: 'wolfram', defaultExtension: 'wl' },
  wxml: { ids: 'wxml', defaultExtension: 'wxml' },
  xml: { ids: 'xml', defaultExtension: 'xml' },
  xsl: { ids: 'xsl', defaultExtension: 'xsl' },
  yaml: { ids: 'yaml', defaultExtension: 'yaml' },
  yang: { ids: 'yang', defaultExtension: 'yang' },
};
