import { IExtensionCollection, IFolderExtension } from '../models/IExtension';
/* tslint:disable max-line-length */
export const extensions: IExtensionCollection<IFolderExtension> = {
  supported: [
    { icon: 'aws', extensions: ['aws'] },
    { icon: 'aws', extensions: ['aws'], dot: true },
    { icon: 'bower', extensions: ['bower_components'] },
    { icon: 'css', extensions: ['css'] },
    { icon: 'dist', extensions: ['dist', 'out', 'export', 'build'] },
    { icon: 'docs', extensions: ['docs'] },
    { icon: 'elasticbeanstalk', extensions: ['elasticbeanstalk', 'ebextensions'], dot: true },
    { icon: 'flow', extensions: ['flow'] },
    { icon: 'git', extensions: ['github', 'git'], dot: true },
    { icon: 'haxelib', extensions: ['haxelib'] },
    { icon: 'images', extensions: ['images', 'img'] },
    { icon: 'less', extensions: ['less'] },
    { icon: 'locale', extensions: ['locale', 'locales'] },
    { icon: 'node', extensions: ['node_modules'], light: true },
    { icon: 'nuget', extensions: ['nuget'], dot: true },
    { icon: 'meteor', extensions: ['meteor'], light: true, dot: true },
    { icon: 'sass', extensions: ['sass', 'scss'], light: true },
    { icon: 'script', extensions: ['script', 'scripts'] },
    { icon: 'src', extensions: ['src', 'source', 'sources'] },
    { icon: 'style', extensions: ['style', 'styles'] },
    { icon: 'test', extensions: ['tests', 'test', '__tests__', '__test__', 'spec', 'specs'] },
    { icon: 'typings', extensions: ['typings'] },
    { icon: 'view', extensions: ['view', 'views'] },
    { icon: 'vscode', extensions: ['vscode'], dot: true },
    { icon: 'webpack', extensions: ['webpack'] },
  ],
};
