import { IExtensionCollection, IFolderExtension } from '../models/IExtension';
/* tslint:disable max-line-length */
export const extensions: IExtensionCollection<IFolderExtension> = {
  supported: [
    { icon: 'aws', extensions: ['aws'], svg: true },
    { icon: 'aws', extensions: ['aws'], dot: true, svg: true },
    { icon: 'bower', extensions: ['bower_components'], svg: true },
    { icon: 'css', extensions: ['css'], svg: true },
    { icon: 'dist', extensions: ['dist', 'out', 'export', 'build'], svg: true },
    { icon: 'docs', extensions: ['docs'], svg: true },
    { icon: 'elasticbeanstalk', extensions: ['elasticbeanstalk', 'ebextensions'], dot: true, svg: true },
    { icon: 'flow', extensions: ['flow'], svg: true},
    { icon: 'git', extensions: ['github', 'git'], dot: true, svg: true },
    { icon: 'haxelib', extensions: ['haxelib'], svg: true },
    { icon: 'images', extensions: ['images', 'img'], svg: true },
    { icon: 'less', extensions: ['less'], svg: true },
    { icon: 'locale', extensions: ['locale', 'locales'], svg: true },
    { icon: 'node', extensions: ['node_modules'], light: true, svg: true },
    { icon: 'nuget', extensions: ['nuget'], dot: true, svg: true },
    { icon: 'meteor', extensions: ['meteor'], light: true, dot: true, svg: true },
    { icon: 'sass', extensions: ['sass', 'scss'], light: true, svg: true },
    { icon: 'script', extensions: ['script', 'scripts'], svg: true},
    { icon: 'src', extensions: ['src', 'source', 'sources'], svg: true },
    { icon: 'style', extensions: ['style', 'styles'], svg: true },
    { icon: 'test', extensions: ['tests', 'test', '__tests__', '__test__', 'spec', 'specs'], svg: true },
    { icon: 'typings', extensions: ['typings'], svg: true },
    { icon: 'view', extensions: ['view', 'views'], svg: true },
    { icon: 'vscode', extensions: ['vscode'], dot: true, svg: true },
    { icon: 'webpack', extensions: ['webpack'], svg: true },
  ],
};
