import type { IFolderCollection } from '../models';

export const extensions: IFolderCollection = {
  default: {
    folder: { icon: 'folder' },
    root_folder: { icon: 'root_folder' },
  },
  supported: [
    {
      icon: 'alpine',
      extensions: ['alpine'],
      light: true,
    },
    { icon: 'android', extensions: ['android'] },
    { icon: 'angular', extensions: ['.angular'] },
    {
      icon: 'apache',
      extensions: ['apache', 'apache2', 'httpd'],
    },
    {
      icon: 'api',
      extensions: ['api', '.api', 'apis', '.apis'],
    },
    {
      icon: 'app',
      extensions: ['app', 'apps', '.app', 'application', 'applications'],
    },
    {
      icon: 'arangodb',
      extensions: ['arangodb', 'arango'],
    },
    {
      icon: 'arch',
      extensions: ['arch'],
    },
    {
      icon: 'asset',
      extensions: ['assets', '.assets'],
    },
    { icon: 'astro', extensions: ['.astro'] },
    {
      icon: 'aurelia',
      extensions: ['aurelia_project'],
    },
    {
      icon: 'audio',
      extensions: [
        'audio',
        '.audio',
        'audios',
        '.audios',
        'sound',
        '.sound',
        'sounds',
        '.sounds',
      ],
    },
    {
      icon: 'auth',
      extensions: ['auth', 'authentication', 'authorisation', 'authorization'],
    },
    { icon: 'aws', extensions: ['aws', '.aws'] },
    { icon: 'azure', extensions: ['azure', '.azure'] },
    {
      icon: 'azurepipelines',
      extensions: [
        'azure-pipelines',
        '.azure-pipelines',
        '.azuredevops',
        '.vsts',
      ],
    },
    { icon: 'binary', extensions: ['bin', '.bin'] },
    { icon: 'bloc', extensions: ['blocs', 'bloc'] },
    {
      icon: 'blueprint',
      extensions: ['blueprint', '.blueprint', 'blueprints', '.blueprints'],
    },
    { icon: 'bot', extensions: ['bot', '.bot'] },
    { icon: 'bower', extensions: ['bower_components'] },
    { icon: 'buildkite', extensions: ['.buildkite'] },
    { icon: 'cake', extensions: ['cake', '.cake'] },
    {
      icon: 'cargo',
      extensions: ['cargo', '.cargo', 'crates'],
    },
    {
      icon: 'certificate',
      extensions: ['certificates', '.certificates', 'certs', 'certs.'],
    },
    { icon: 'changesets', extensions: ['.changeset'] },
    { icon: 'chef', extensions: ['chef', '.chef'] },
    { icon: 'circleci', extensions: ['.circleci'] },
    { icon: 'claude', extensions: ['.claude'] },
    {
      icon: 'cloudflare',
      extensions: ['.cloudflare', 'cloudflare'],
    },
    {
      icon: 'controller',
      extensions: [
        '__controller__',
        '__controllers__',
        'controller',
        'controllers',
        '.controllers',
        '__handler__',
        '__handlers__',
        'handler',
        '.handler',
        'handlers',
        '.handlers',
      ],
    },
    {
      icon: 'component',
      extensions: [
        'component',
        'components',
        '.components',
        'gui',
        'src-ui',
        'ui',
        'widgets',
      ],
    },
    {
      icon: 'composer',
      extensions: ['composer', '.composer'],
    },
    {
      icon: 'cli',
      extensions: [
        'cli',
        'cmd',
        'command',
        'commands',
        'commandline',
        'console',
      ],
    },
    {
      icon: 'client',
      extensions: ['client', 'clients'],
    },
    { icon: 'cmake', extensions: ['.cmake', 'cmake'] },
    {
      icon: 'common',
      extensions: ['common'],
    },
    {
      icon: 'config',
      extensions: [
        'conf',
        '.conf',
        'cfg',
        '.cfg',
        'cfgs',
        '.cfgs',
        'config',
        '.config',
        'configs',
        '.configs',
        'configuration',
        '.configuration',
        'configurations',
        '.configurations',
        'setting',
        '.setting',
        'settings',
        '.settings',
        'ini',
        '.ini',
        'initializers',
        '.initializers',
      ],
    },
    { icon: 'coverage', extensions: ['coverage'] },
    {
      icon: 'css',
      extensions: ['css', '_css'],
    },
    {
      icon: 'css2',
      extensions: ['css', '_css'],
      disabled: true,
    },
    { icon: 'cubit', extensions: ['cubits', 'cubit'] },
    {
      icon: 'cursor',
      extensions: ['.cursor'],
      light: true,
    },
    {
      icon: 'cypress',
      extensions: ['cypress'],
      light: true,
    },
    {
      icon: 'dapr',
      extensions: ['.dapr', 'dapr'],
    },
    {
      icon: 'dart',
      extensions: ['dart', '.dart_tool'],
    },
    {
      icon: 'databricks',
      extensions: ['.databricks'],
    },
    {
      icon: 'datadog',
      extensions: ['datadog', '.datadog'],
    },
    {
      icon: 'db',
      extensions: [
        'db',
        'database',
        'sql',
        'data',
        'repo',
        'repository',
        'repositories',
        'store',
        'stores',
        'storage',
        'storages',
      ],
    },
    {
      icon: 'debian',
      extensions: ['debian', 'deb'],
    },
    {
      icon: 'dependabot',
      extensions: ['.dependabot'],
    },
    {
      icon: 'devcontainer',
      extensions: ['.devcontainer'],
    },
    {
      icon: 'devenv',
      extensions: ['.devenv'],
      light: true,
    },
    {
      icon: 'dist',
      extensions: [
        'dist',
        '.dist',
        'dists',
        'out',
        'outs',
        'output',
        'outputs',
        'export',
        'exports',
        'build',
        '.build',
        'builds',
        'release',
        'releases',
        'target',
        'targets',
      ],
    },
    {
      icon: 'docker',
      extensions: ['docker', '.docker'],
    },
    {
      icon: 'docs',
      extensions: ['docs', 'doc', 'document', 'documents'],
    },
    { icon: 'e2e', extensions: ['e2e'] },
    {
      icon: 'elasticbeanstalk',
      extensions: ['.elasticbeanstalk', '.ebextensions'],
    },
    {
      icon: 'electron',
      extensions: ['electron'],
      light: true,
    },
    {
      icon: 'environments',
      extensions: ['environments'],
    },
    {
      icon: 'expo',
      extensions: ['.expo', '.expo-shared'],
      light: true,
    },
    {
      icon: 'favicon',
      extensions: ['favicon', 'favicons'],
    },
    {
      icon: 'fedora',
      extensions: ['fedora'],
      light: true,
    },
    {
      icon: 'frontcommerce',
      extensions: ['.front-commerce'],
    },
    {
      icon: 'flow',
      extensions: ['flow', 'flow-typed'],
    },
    {
      icon: 'flutter',
      extensions: ['flutter', 'Flutter'],
    },
    {
      icon: 'fonts',
      extensions: ['fonts', 'font', 'fnt', 'webfonts'],
      light: true,
    },
    { icon: 'gcp', extensions: ['gcp', '.gcp'] },
    {
      icon: 'gentoo',
      extensions: ['gentoo'],
    },
    { icon: 'gemini', extensions: ['.gemini'] },
    {
      icon: 'git',
      extensions: ['.git', 'submodules', '.submodules'],
    },
    { icon: 'github', extensions: ['.github'] },
    { icon: 'gitlab', extensions: ['.gitlab'] },
    { icon: 'godot', extensions: ['godot', '.godot'] },
    {
      icon: 'gradle',
      extensions: ['gradle', '.gradle'],
      light: true,
    },
    { icon: 'graphql', extensions: ['graphql'] },
    { icon: 'grok', extensions: ['.grok'] },
    { icon: 'grunt', extensions: ['grunt'] },
    {
      icon: 'gulp',
      extensions: [
        'gulp',
        'gulpfile.js',
        'gulpfile.coffee',
        'gulpfile.ts',
        'gulpfile.babel.js',
        'gulpfile.babel.coffee',
        'gulpfile.babel.ts',
      ],
    },
    {
      icon: 'haxelib',
      extensions: ['.haxelib', 'haxe_libraries'],
    },
    {
      icon: 'helper',
      extensions: ['helper', '.helper', 'helpers', '.helpers'],
    },
    {
      icon: 'histoire',
      extensions: ['.histoire'],
    },
    {
      icon: 'hook',
      extensions: ['hook', '.hook', 'hooks', '.hooks'],
    },
    {
      icon: 'husky',
      extensions: ['.husky'],
    },
    { icon: 'idea', extensions: ['.idea'] },
    {
      icon: 'images',
      extensions: [
        '.fig',
        '.figs',
        'images',
        'image',
        '.img',
        'img',
        '.imgs',
        'imgs',
        'icons',
        'icon',
        'ico',
        'screenshot',
        'screenshots',
        'svg',
        'texture',
        'textures',
      ],
    },
    {
      icon: 'include',
      extensions: [
        'include',
        'includes',
        'incl',
        'inc',
        '.include',
        '.includes',
        '.incl',
        '.inc',
        '_include',
        '_includes',
        '_incl',
        '_inc',
      ],
    },
    {
      icon: 'interfaces',
      extensions: ['interface', 'interfaces'],
    },
    { icon: 'ios', extensions: ['ios'] },
    { icon: 'js', extensions: ['js'] },
    { icon: 'json', extensions: ['json'] },
    {
      icon: 'json_official',
      extensions: ['json'],
      disabled: true,
    },
    { icon: 'junie', extensions: ['.junie'] },
    { icon: 'kadence', extensions: ['.kadence'] },
    { icon: 'kiro', extensions: ['.kiro'] },
    {
      icon: 'kotlin',
      extensions: ['kotlin', 'Kotlin', '.kotlin'],
    },
    {
      icon: 'kubernetes',
      extensions: [
        'kubernetes',
        'k8s',
        'kube',
        'kuber',
        '.kubernetes',
        '.k8s',
        '.kube',
        '.kuber',
      ],
    },
    { icon: 'less', extensions: ['less', '_less'] },
    {
      icon: 'library',
      extensions: [
        'lib',
        'libs',
        '.lib',
        '.libs',
        '__lib__',
        '__libs__',
        'library',
        'libraries',
      ],
    },
    { icon: 'linux', extensions: ['linux'] },
    {
      icon: 'locale',
      extensions: [
        'lang',
        'language',
        'languages',
        'locale',
        'locales',
        '_locale',
        '_locales',
        'internationalization',
        'globalization',
        'localization',
        'i18n',
        'g11n',
        'l10n',
        'translation',
        'translations',
      ],
    },
    {
      icon: 'log',
      extensions: ['log', 'logs', 'logging', 'logger', 'loggers'],
    },
    { icon: 'macos', extensions: ['macos', 'darwin'] },
    {
      icon: 'mariadb',
      extensions: ['mariadb', 'maria'],
    },
    { icon: 'maven', extensions: ['.mvn'] },
    {
      icon: 'mediawiki',
      extensions: ['mediawiki'],
    },
    {
      icon: 'memcached',
      extensions: ['memcached', '.memcached'],
    },
    {
      icon: 'meteor',
      extensions: ['.meteor'],
      light: true,
    },
    {
      icon: 'middleware',
      extensions: ['middleware', 'middlewares'],
    },
    { icon: 'mjml', extensions: ['mjml', '.mjml'] },
    {
      icon: 'minecraft',
      extensions: ['.minecraft'],
    },
    {
      icon: 'minikube',
      extensions: ['minikube', 'minik8s', 'minikuber'],
    },
    {
      icon: 'mobile',
      extensions: ['mobile', 'mobiles', '.mobile', '.mobiles'],
    },
    {
      icon: 'mojo',
      extensions: ['mojo'],
    },
    {
      icon: 'mock',
      extensions: ['mocks', '.mocks', '__mocks__'],
    },
    {
      icon: 'model',
      extensions: [
        'model',
        '.model',
        'models',
        '.models',
        'entities',
        '.entities',
      ],
    },
    {
      icon: 'module',
      extensions: ['modules'],
    },
    {
      icon: 'mongodb',
      extensions: ['mongodb', 'mongo'],
    },
    {
      icon: 'mypy',
      extensions: ['.mypy_cache'],
      light: true,
    },
    {
      icon: 'mysql',
      extensions: ['mysqldb', 'mysql'],
      light: true,
    },

    {
      icon: 'netlify',
      extensions: ['netlify'],
    },
    { icon: 'next', extensions: ['.next'] },
    { icon: 'nginx', extensions: ['nginx', 'conf.d'] },
    {
      icon: 'nix',
      extensions: ['.niv', '.nix', 'nix', 'niv'],
    },
    {
      icon: 'node',
      extensions: ['node_modules'],
      light: true,
    },
    {
      icon: 'notebooks',
      extensions: ['notebooks', 'notebook'],
    },
    {
      icon: 'notification',
      extensions: ['notification', 'notifications', 'event', 'events'],
    },
    { icon: 'nuget', extensions: ['.nuget'] },
    { icon: 'ohpm', extensions: ['oh_modules'] },
    {
      icon: 'ocx',
      extensions: ['.ocx'],
      light: true,
    },
    {
      icon: 'package',
      extensions: ['package', 'packages', '.package', '.packages', 'pkg'],
    },
    { icon: 'paket', extensions: ['.paket'] },
    { icon: 'php', extensions: ['php'] },
    {
      icon: 'platformio',
      extensions: ['.pio', '.pioenvs'],
    },
    {
      icon: 'plugin',
      extensions: [
        'plugin',
        '.plugin',
        'plugins',
        '.plugins',
        'extension',
        '.extension',
        'extensions',
        '.extensions',
      ],
    },
    { icon: 'prisma', extensions: ['prisma'] },
    {
      icon: 'private',
      extensions: ['private', '.private'],
    },
    {
      icon: 'public',
      extensions: ['public', '.public'],
    },
    {
      icon: 'pytest',
      extensions: ['.pytest_cache'],
    },
    {
      icon: 'python',
      extensions: ['.venv', '.virtualenv', '__pycache__'],
    },
    {
      icon: 'vercel',
      extensions: ['.vercel'],
    },
    {
      icon: 'vitepress',
      extensions: ['.vitepress'],
    },
    { icon: 'redis', extensions: ['redis'] },
    { icon: 'ravendb', extensions: ['ravendb'] },
    {
      icon: 'route',
      extensions: ['route', 'routes', '_route', '_routes', 'router', 'routers'],
    },
    {
      icon: 'redhat',
      extensions: ['redhat', 'rhel'],
    },
    {
      icon: 'redux',
      extensions: ['redux'],
      light: true,
    },

    {
      icon: 'nuxt',
      extensions: ['nuxt', '.nuxt'],
    },
    {
      icon: 'sass',
      extensions: ['sass', 'scss', '_sass', '_scss'],
      light: true,
    },
    {
      icon: 'schema',
      extensions: ['schema', 'schemas'],
    },
    {
      icon: 'script',
      extensions: ['script', 'scripts'],
    },
    {
      icon: 'seedkit',
      extensions: ['seedkit', '.seedkit'],
    },
    { icon: 'server', extensions: ['server'] },
    {
      icon: 'services',
      extensions: ['service', 'services'],
    },
    {
      icon: 'shared',
      extensions: [
        'share',
        'shared',
        '.share',
        '.shared',
        '__shared__',
        '__share__',
      ],
    },
    {
      icon: 'slackware',
      extensions: ['slackware'],
    },
    {
      icon: 'snaplet',
      extensions: ['.snaplet'],
    },
    {
      icon: 'spin',
      extensions: ['.spin'],
    },
    {
      icon: 'src',
      extensions: ['src', 'source', 'sources', '__src__'],
    },
    {
      icon: 'sso',
      extensions: ['sso'],
    },
    {
      icon: 'story',
      extensions: ['story', 'stories', '__stories__', '.storybook'],
    },
    { icon: 'style', extensions: ['style', 'styles'] },
    {
      icon: 'supabase',
      extensions: ['supabase'],
    },
    {
      icon: 'suse',
      extensions: ['suse', 'opensuse'],
    },
    {
      icon: 'svelte',
      extensions: ['svelte', '.svelte-kit'],
    },
    {
      icon: 'swagger',
      extensions: ['swagger'],
    },
    { icon: 'tauri', extensions: ['src-tauri'] },
    {
      icon: 'telegram',
      extensions: ['telegram', '.telegram', 'Telegram', 'TelegramDesktop'],
    },
    {
      icon: 'test',
      extensions: [
        'tests',
        '.tests',
        'test',
        '.test',
        '__tests__',
        '__test__',
        'spec',
        '.spec',
        'specs',
        '.specs',
        'integration',
      ],
    },
    {
      icon: 'temp',
      extensions: ['temp', '.temp', 'tmp', '.tmp'],
    },
    {
      icon: 'template',
      extensions: ['template', '.template', 'templates', '.templates'],
    },
    { icon: 'theme', extensions: ['theme', 'themes'] },
    { icon: 'travis', extensions: ['.travis'] },
    {
      icon: 'tools',
      extensions: [
        'tool',
        'tools',
        '.tools',
        'util',
        'utils',
        'utilities',
        'tooling',
      ],
    },
    {
      icon: 'trunk',
      extensions: ['.trunk'],
    },
    {
      icon: 'turbo',
      extensions: ['.turbo'],
    },
    {
      icon: 'typescript',
      extensions: ['typescript', 'ts'],
    },
    {
      icon: 'typings',
      extensions: ['typings', 'types', '@types'],
    },
    {
      icon: 'typings2',
      extensions: ['typings', 'types', '@types'],
      disabled: true,
    },
    {
      icon: 'vagrant',
      extensions: ['vagrant', '.vagrant'],
    },
    {
      icon: 'video',
      extensions: ['video', '.video', 'videos', '.videos'],
    },
    {
      icon: 'view',
      extensions: [
        'html',
        'view',
        'views',
        'layout',
        'layouts',
        'page',
        'pages',
        '_view',
        '_views',
        '_layout',
        '_layouts',
        '_page',
        '_pages',
      ],
    },
    {
      icon: 'void',
      extensions: ['void'],
    },
    { icon: 'vs', extensions: ['.vs'] },
    {
      icon: 'vs2',
      extensions: ['.vs'],
      disabled: true,
    },
    {
      icon: 'vscode',
      extensions: ['.vscode', 'vscode'],
    },
    {
      icon: 'vscode2',
      extensions: ['.vscode', 'vscode'],
      disabled: true,
    },
    {
      icon: 'vscode3',
      extensions: ['.vscode', 'vscode'],
      disabled: true,
    },
    {
      icon: 'vscode_test',
      extensions: ['.vscode-test'],
    },
    {
      icon: 'vscode_test2',
      extensions: ['.vscode-test'],
      disabled: true,
    },
    {
      icon: 'vscode_test3',
      extensions: ['.vscode-test'],
      disabled: true,
    },
    {
      icon: 'wasm',
      extensions: ['wasm', 'WASM', 'webassembly', 'WebAssembly'],
    },
    {
      icon: 'wasp',
      extensions: ['.wasp'],
    },
    {
      icon: 'wit',
      extensions: ['wit'],
    },
    {
      icon: 'webpack',
      extensions: ['webpack', '.webpack'],
    },
    {
      icon: 'windows',
      extensions: ['windows', 'win32'],
    },
    {
      icon: 'windsurf',
      extensions: ['.windsurf'],
    },
    {
      icon: 'www',
      extensions: ['.web', 'www', 'wwwroot', 'web'],
    },
    {
      icon: 'yarn',
      extensions: ['.yarn'],
    },
    {
      icon: 'zed',
      extensions: ['.zed'],
      light: true,
    },
  ],
};
