name: Code Coverage

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed

permissions:
  contents: read
  code-quality: write
  actions: read

jobs:
  code_coverage:
    name: Send code coverage report to GitHub Code Quality
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.repository_owner == 'vscode-icons' &&
      github.actor != 'dependabot[bot]'
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v7
        with:
          name: code-coverage-report-${{ github.event.workflow_run.id }}
          path: coverage
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload code coverage report
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage/cobertura-coverage.xml
          language: TypeScript
          label: code-coverage/nyc
